NAME = hello
SRCS = hello.c
include $(NAVY_HOME)/Makefile

$(shell cp ./build/$(NAME)-riscv64 ../../../nanos-lite/build/ramdisk.img)
$(shell cp ./build/$(NAME)-riscv64.elf ../../../nanos-lite/build/ramdisk.elf)